name: Testar API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  teste-api:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/setup-python@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.6'

      - name: Instalar dependências
        run: |
          pip install fastapi uvicorn

      - name: Testar se a API responde corretamente
        run: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Aguarda o servidor iniciar
          curl --fail http://127.0.0.1:8000/livros  # Testa a rota /livros
          curl --fail http://127.0.0.1:8000/autores  # Testa a rota /autores
