name: Testar API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  teste-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.6'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Criar arquivo dados.json de teste
        run: |
          echo '{
            "livros": [
              {"id": 1, "titulo": "Teste"}
            ],
            "autores": [
              {"id": 1, "nome": "Autor Teste"}
            ]
          }' > dados.json

      - name: Testar se a API responde corretamente
        run: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Aguarda o servidor iniciar
          curl --fail http://127.0.0.1:8000/livros
          curl --fail http://127.0.0.1:8000/autores
